version: '2'
services:
  datastore:
    image: busybox
    volumes:
      - bundle_install:/app/vendor/bundle
      - node_modules:/app/node_modules
      - mysql_data:/var/lib/mysql
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: quick_busters_development
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
    ports:
      - "3306:3306"
  web:
    build: .
    command: bundle exec rails s -b '0.0.0.0'
    volumes:
      - .:/app
      - bundle_install:/app/vendor/bundle
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes_from:
      - datastore
volumes:
  bundle_install:
    driver: local
  node_modules:
    driver: local
  mysql_data:
    driver: local

